name: Tracking issue
description: Issue to track several related items .
labels: ["tracking"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description.
      description: |
        Add extra information about what is being tracked by this issue.
      placeholder: |
        N/A
    validations:
      required: true
  - type: textarea
    id: tracked
    attributes:
      label: Checklist.
      description: |
        Provide a checklist of the things that are being tracked.
    validations:
      required: true